# Generated by Django 2.2.5 on 2020-01-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleaccounttb',
            name='iss',
            field=models.CharField(max_length=128, unique=True, verbose_name='issue ID'),
        ),
        migrations.AlterField(
            model_name='appleaccounttb',
            name='kid',
            field=models.CharField(max_length=128, unique=True, verbose_name='key ID'),
        ),
    ]
