# Generated by Django 2.2.5 on 2020-01-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0002_auto_20200111_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='appleaccounttb',
            name='csr',
            field=models.TextField(default='', verbose_name='csr 证书'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appleaccounttb',
            name='p12',
            field=models.CharField(max_length=128, unique=True, verbose_name='p12 文件名'),
        ),
        migrations.AlterField(
            model_name='appleaccounttb',
            name='p8',
            field=models.TextField(verbose_name='p8 证书'),
        ),
        migrations.AlterField(
            model_name='appleaccounttb',
            name='status',
            field=models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=0, verbose_name='是否启用'),
        ),
    ]
