# Generated by Django 2.2.5 on 2020-01-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0003_auto_20200112_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appleaccounttb',
            name='csr',
        ),
    ]
