# Generated by Django 2.2.5 on 2020-01-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0004_remove_appleaccounttb_csr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleaccounttb',
            name='bundleid',
            field=models.CharField(default='null', max_length=64, verbose_name='bundle ID'),
        ),
        migrations.AlterField(
            model_name='appleaccounttb',
            name='cer_id',
            field=models.CharField(default='null', max_length=64, verbose_name='证书 ID'),
        ),
        migrations.AlterField(
            model_name='appleaccounttb',
            name='iss',
            field=models.CharField(max_length=128, verbose_name='issue ID'),
        ),
        migrations.AlterField(
            model_name='appleaccounttb',
            name='kid',
            field=models.CharField(max_length=128, verbose_name='key ID'),
        ),
        migrations.AlterField(
            model_name='appleaccounttb',
            name='p12',
            field=models.CharField(default='null', max_length=128, verbose_name='p12 文件名'),
        ),
    ]
