# Generated by Django 2.2.5 on 2020-01-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0006_appleaccounttb_cer_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleaccounttb',
            name='cer_content',
            field=models.TextField(null=True, verbose_name='证书 详情'),
        ),
    ]
