# Generated by Django 2.2.5 on 2020-01-16 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0007_auto_20200112_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleDeviceTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udid', models.CharField(max_length=128, verbose_name='设备 udid')),
                ('apple_id', models.IntegerField(verbose_name='关联的苹果账号 id')),
                ('device_id', models.CharField(max_length=64, verbose_name='设备注册 ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生成的日期')),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1, verbose_name='是否启用')),
            ],
        ),
    ]
