# Generated by Django 2.2.5 on 2020-01-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0008_appledevicetb'),
    ]

    operations = [
        migrations.AddField(
            model_name='appledevicetb',
            name='device_model',
            field=models.CharField(max_length=64, null=True, verbose_name='设备型号'),
        ),
        migrations.AddField(
            model_name='appledevicetb',
            name='device_name',
            field=models.CharField(max_length=64, null=True, verbose_name='设备名'),
        ),
    ]
