# Generated by Django 2.2.5 on 2020-01-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0009_auto_20200116_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleaccounttb',
            name='bundleid',
            field=models.CharField(default='null', max_length=64, null=True, verbose_name='bundle ID'),
        ),
        migrations.AlterField(
            model_name='appleaccounttb',
            name='p12',
            field=models.CharField(default='null', max_length=128, null=True, verbose_name='p12 文件名'),
        ),
    ]
