# Generated by Django 2.2.5 on 2020-01-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0011_auto_20200118_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleaccounttb',
            name='bundleid',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='bundle ID'),
        ),
        migrations.AlterField(
            model_name='appleaccounttb',
            name='p12',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='p12 文件名'),
        ),
    ]
