# Generated by Django 2.2.5 on 2020-01-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0012_auto_20200118_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleaccounttb',
            name='cer_content',
            field=models.TextField(blank=True, null=True, verbose_name='证书 详情'),
        ),
        migrations.AlterField(
            model_name='appleaccounttb',
            name='cer_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='证书 ID'),
        ),
        migrations.AlterField(
            model_name='appledevicetb',
            name='device_model',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='设备型号'),
        ),
        migrations.AlterField(
            model_name='appledevicetb',
            name='device_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='设备名'),
        ),
    ]
