# Generated by Django 2.2.5 on 2020-01-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('apple', '0013_auto_20200118_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='appleaccounttb',
            name='customer',
            field=models.ManyToManyField(blank=True, to='customer.CustomerTb'),
        ),
    ]
