# Generated by Django 2.2.5 on 2020-01-18 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0015_remove_appleaccounttb_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='IOS 包名')),
                ('icon', models.CharField(blank=True, max_length=128, null=True, verbose_name='Icon 地址')),
                ('version', models.CharField(max_length=8, verbose_name='IOS 包版本号')),
                ('build_version', models.CharField(max_length=8, verbose_name='创建 版本号')),
                ('mini_version', models.CharField(max_length=8, verbose_name='最低适配IOS版本号')),
                ('ipa', models.CharField(max_length=128, verbose_name='IOS 包地址')),
                ('mobileconfig', models.CharField(max_length=128, verbose_name='mobileconfig 包地址')),
                ('total_count', models.IntegerField(default=0, verbose_name='当前下载量')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生成的日期')),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1, verbose_name='是否启用')),
            ],
        ),
        migrations.AlterField(
            model_name='appleaccounttb',
            name='p12',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='p12 地址'),
        ),
    ]
