# Generated by Django 2.2.5 on 2020-01-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0016_auto_20200118_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetb',
            name='mobileconfig',
            field=models.CharField(max_length=128, verbose_name='mobileconfig 地址'),
        ),
    ]
