# Generated by Django 2.2.5 on 2020-01-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0017_auto_20200118_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetb',
            name='bundle_identifier',
            field=models.CharField(default='com.chuangle.bet365', max_length=32, verbose_name='BundleId'),
            preserve_default=False,
        ),
    ]
