# Generated by Django 2.2.5 on 2020-01-19 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0018_packagetb_bundle_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagetb',
            old_name='total_count',
            new_name='count',
        ),
    ]
