# Generated by Django 2.2.5 on 2020-01-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0019_auto_20200119_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetb',
            name='customer',
            field=models.IntegerField(default=1, verbose_name='业主'),
        ),
    ]
