# Generated by Django 2.2.5 on 2020-01-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0020_packagetb_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appleaccounttb',
            name='bundleid',
        ),
        migrations.AddField(
            model_name='appleaccounttb',
            name='bundleIds',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='苹果 bundleIds'),
        ),
    ]
