# Generated by Django 2.2.5 on 2020-01-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0022_appleaccounttb_bundleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleaccounttb',
            name='bundleId',
            field=models.CharField(default='com.app.*', max_length=64, verbose_name='bundleId'),
        ),
    ]
