# Generated by Django 2.2.5 on 2020-01-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0023_auto_20200120_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsrTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, unique=True, verbose_name='csr 名称')),
                ('csr_content', models.TextField(verbose_name='证书 详情')),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1, verbose_name='是否启用')),
            ],
        ),
    ]
