# Generated by Django 2.2.5 on 2020-01-22 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0024_csrtb'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageIstalledTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.IntegerField(verbose_name='包ID')),
                ('package_name', models.CharField(max_length=12, verbose_name='IOS包名')),
                ('device_id', models.CharField(max_length=64, verbose_name='设备注册ID')),
                ('device_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='设备名')),
                ('device_model', models.CharField(blank=True, max_length=64, null=True, verbose_name='设备型号')),
                ('customer_id', models.IntegerField(default=1, verbose_name='业主')),
                ('customer_name', models.CharField(max_length=12, verbose_name='业主名称')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生成的日期')),
                ('is_first_install', models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1, verbose_name='是否是第一次注册安装')),
                ('install_status', models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1, verbose_name='是否安装成功')),
            ],
        ),
    ]
