# Generated by Django 2.2.5 on 2020-01-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0025_packageistalledtb'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageistalledtb',
            name='package_version',
            field=models.CharField(default=0, max_length=8, verbose_name='IOS 包版本号'),
            preserve_default=False,
        ),
    ]
