# Generated by Django 2.2.5 on 2020-01-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0027_auto_20200122_0501'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackageIstalledTb',
            new_name='PackageInstalledTb',
        ),
    ]
