# Generated by Django 2.2.5 on 2020-02-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0028_auto_20200122_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetb',
            name='apk',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='APK 包地址'),
        ),
        migrations.AlterField(
            model_name='packageinstalledtb',
            name='device_udid',
            field=models.CharField(max_length=64, verbose_name='设备UDID'),
        ),
    ]
