# Generated by Django 2.2.5 on 2020-03-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0029_auto_20200228_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetb',
            name='build_version',
            field=models.CharField(max_length=32, verbose_name='创建 版本号'),
        ),
        migrations.AlterField(
            model_name='packagetb',
            name='mini_version',
            field=models.CharField(max_length=32, verbose_name='最低适配IOS版本号'),
        ),
        migrations.AlterField(
            model_name='packagetb',
            name='name',
            field=models.CharField(max_length=64, verbose_name='IOS 包名'),
        ),
        migrations.AlterField(
            model_name='packagetb',
            name='version',
            field=models.CharField(max_length=32, verbose_name='IOS 包版本号'),
        ),
    ]
