# Generated by Django 2.2.5 on 2020-01-18 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='业主 名称')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生成的日期')),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=0, verbose_name='是否启用')),
            ],
        ),
    ]
