# Generated by Django 2.2.5 on 2020-01-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0015_remove_appleaccounttb_customer'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertb',
            name='apple_account',
            field=models.ManyToManyField(blank=True, to='apple.AppleAccountTb', verbose_name='苹果账号'),
        ),
    ]
