# Generated by Django 2.2.5 on 2020-01-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0019_auto_20200119_0309'),
        ('customer', '0002_customertb_apple_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertb',
            name='package',
            field=models.ManyToManyField(blank=True, to='apple.PackageTb', verbose_name='Package'),
        ),
    ]
