# Generated by Django 2.2.5 on 2020-01-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customertb_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertb',
            name='package',
        ),
    ]
