# Generated by Django 2.2.5 on 2020-01-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alioss', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aliossbuckettb',
            unique_together={('bucket_name', 'main_host')},
        ),
    ]
